name: CI

on:
  push:
<<<<<<< HEAD
    branches: [ production ]
  pull_request:
    branches: [ production ]
=======
    branches: [ main ]
  pull_request:
    branches: [ main ]
>>>>>>> 434d795 (Updated dotnet version on yaml, fixed login page breadcrumb with response url on Program.cs, and made adjustments to UI with css file)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.204'
        
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
<<<<<<< HEAD
      if: github.ref == 'refs/heads/production' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
        git push heroku HEAD:production
=======
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
        git push heroku HEAD:main
>>>>>>> 434d795 (Updated dotnet version on yaml, fixed login page breadcrumb with response url on Program.cs, and made adjustments to UI with css file)
